# Generated by Django 5.2 on 2025-05-22 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the department.', max_length=255, unique=True, verbose_name='Department Name')),
                ('slug', models.SlugField(help_text='A short label for URL configuration.', max_length=255, unique=True, verbose_name='Department Slug')),
                ('description', models.TextField(blank=True, default='', help_text='A brief description of the department.', verbose_name='Department Description')),
            ],
            options={
                'verbose_name': 'Employee Department',
                'verbose_name_plural': 'Employee Departments',
                'ordering': ['name'],
                'permissions': [('can_view_department', 'Can view department'), ('can_edit_department', 'Can edit department'), ('can_delete_department', 'Can delete department')],
                'indexes': [models.Index(fields=['name'], name='employees_e_name_9279ae_idx'), models.Index(fields=['slug'], name='employees_e_slug_4ea3a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_department_name'), models.UniqueConstraint(fields=('slug',), name='unique_department_slug')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the position.', max_length=255, unique=True, verbose_name='Position Name')),
                ('slug', models.SlugField(help_text='A short label for URL configuration.', max_length=255, unique=True, verbose_name='Position Slug')),
                ('description', models.TextField(blank=True, default='', help_text='A brief description of the position.', verbose_name='Position Description')),
            ],
            options={
                'verbose_name': 'Employee Position',
                'verbose_name_plural': 'Employee Positions',
                'ordering': ['name'],
                'permissions': [('can_view_position', 'Can view position'), ('can_edit_position', 'Can edit position'), ('can_delete_position', 'Can delete position')],
                'indexes': [models.Index(fields=['name'], name='employees_e_name_2e175d_idx'), models.Index(fields=['slug'], name='employees_e_slug_abc4c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_position_name'), models.UniqueConstraint(fields=('slug',), name='unique_position_slug')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The person's first name.", max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="The person's last name.", max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="The person's email address.", max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, default='', help_text="The person's phone number.", max_length=20, verbose_name='Phone Number')),
                ('hire_date', models.DateField(help_text='The date the employee was hired.', verbose_name='Hire Date')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the employee is currently active.', verbose_name='Is Active')),
                ('salary', models.DecimalField(decimal_places=2, help_text='The salary of the employee.', max_digits=10, verbose_name='Salary')),
                ('department', models.ForeignKey(help_text='The department the employee belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.employeedepartment', verbose_name='Department')),
                ('position', models.ForeignKey(help_text='The position of the employee.', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.employeeposition', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('can_view_employee', 'Can view employee'), ('can_edit_employee', 'Can edit employee'), ('can_delete_employee', 'Can delete employee')],
                'abstract': False,
                'indexes': [models.Index(fields=['last_name'], name='employees_e_last_na_ae2876_idx'), models.Index(fields=['first_name'], name='employees_e_first_n_ac154b_idx')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_employee_email')],
            },
        ),
    ]
