# Generated by Django 5.2 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_view_employee', 'Can view employee'), ('can_edit_employee', 'Can edit employee'), ('can_delete_employee', 'Can delete employee'), ('can_add_employee', 'Can add employee')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeedepartment',
            options={'ordering': ['name'], 'permissions': [('can_view_department', 'Can view department'), ('can_edit_department', 'Can edit department'), ('can_delete_department', 'Can delete department'), ('can_add_department', 'Can add department')], 'verbose_name': 'Employee Department', 'verbose_name_plural': 'Employee Departments'},
        ),
        migrations.AlterModelOptions(
            name='employeeposition',
            options={'ordering': ['name'], 'permissions': [('can_view_position', 'Can view position'), ('can_edit_position', 'Can edit position'), ('can_delete_position', 'Can delete position'), ('can_add_position', 'Can add position')], 'verbose_name': 'Employee Position', 'verbose_name_plural': 'Employee Positions'},
        ),
    ]
