# Generated by Django 5.2 on 2025-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_is_active_employee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rut',
            field=models.CharField(default='', help_text="The person's RUT (Rol Único Tributario).", max_length=13, unique=True, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
