services:
  docs:
    image: erp_villa_alemana_escolares_tecnologicos_local_docs
    container_name: erp_villa_alemana_escolares_tecnologicos_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./erp_villa_alemana_escolares_tecnologicos:/app/erp_villa_alemana_escolares_tecnologicos:z
    ports:
      - '9000:9000'
    command: /start-docs
