# Generated by Django 5.2 on 2025-05-21 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the province.', max_length=64, unique=True, verbose_name='Province name')),
                ('cod', models.CharField(help_text='The code of the province.', max_length=32, unique=True, verbose_name='Province code')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('name',),
                'permissions': [('can_view_province', 'Can view province'), ('can_edit_province', 'Can edit province'), ('can_delete_province', 'Can delete province')],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the comuna.', max_length=64, unique=True, verbose_name='Comuna name')),
                ('cod', models.CharField(help_text='The code of the comuna.', max_length=32, unique=True, verbose_name='Comuna code')),
                ('province', models.ForeignKey(help_text='The province of the comuna.', on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='addresses.province', verbose_name='Comuna province')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ('name',),
                'permissions': [('can_view_comuna', 'Can view comuna'), ('can_edit_comuna', 'Can edit comuna'), ('can_delete_comuna', 'Can delete comuna')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the region.', max_length=64, unique=True, verbose_name='Region name')),
                ('cod', models.CharField(help_text='The code of the region.', max_length=32, unique=True, verbose_name='Region code')),
                ('number', models.CharField(help_text='The number of the region.', max_length=32, unique=True, verbose_name='Region number')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('number',),
                'permissions': [('can_view_region', 'Can view region'), ('can_edit_region', 'Can edit region'), ('can_delete_region', 'Can delete region')],
                'indexes': [models.Index(fields=['name'], name='region_name_idx'), models.Index(fields=['cod'], name='region_cod_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_region_name'), models.UniqueConstraint(fields=('cod',), name='unique_region_cod')],
            },
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(help_text='The region of the province.', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='addresses.region', verbose_name='Province region'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Street name', max_length=96, verbose_name='Street name')),
                ('number', models.PositiveSmallIntegerField(help_text='Street number', verbose_name='Street Number')),
                ('apartment', models.CharField(blank=True, default='', help_text='Apartment number', max_length=16, verbose_name='Apartment')),
                ('floor', models.CharField(blank=True, default='', help_text='Floor number', max_length=16, verbose_name='Floor')),
                ('description', models.TextField(blank=True, default='', help_text='A brief description of the address.', verbose_name='Description')),
                ('postal_code', models.CharField(blank=True, default='', help_text='The postal code of the address.', max_length=20, verbose_name='Postal Code')),
                ('comuna', models.ForeignKey(help_text='The comuna of the address.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='addresses.comuna', verbose_name='Comuna')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ('street', 'number'),
                'permissions': [('can_view_address', 'Can view address'), ('can_edit_address', 'Can edit address'), ('can_delete_address', 'Can delete address')],
                'indexes': [models.Index(fields=['street'], name='address_street_idx'), models.Index(fields=['number'], name='address_number_idx')],
                'constraints': [models.UniqueConstraint(fields=('street', 'number'), name='unique_address_street_number')],
            },
        ),
        migrations.AddIndex(
            model_name='comuna',
            index=models.Index(fields=['name'], name='comuna_name_idx'),
        ),
        migrations.AddIndex(
            model_name='comuna',
            index=models.Index(fields=['cod'], name='comuna_cod_idx'),
        ),
        migrations.AddConstraint(
            model_name='comuna',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_comuna_name'),
        ),
        migrations.AddConstraint(
            model_name='comuna',
            constraint=models.UniqueConstraint(fields=('cod',), name='unique_comuna_cod'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['name'], name='province_name_idx'),
        ),
        migrations.AddIndex(
            model_name='province',
            index=models.Index(fields=['cod'], name='province_cod_idx'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_province_name'),
        ),
        migrations.AddConstraint(
            model_name='province',
            constraint=models.UniqueConstraint(fields=('cod',), name='unique_province_cod'),
        ),
    ]
