# Generated by Django 5.2 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('street', 'number'), 'permissions': [('can_view_address', 'Can view address'), ('can_edit_address', 'Can edit address'), ('can_delete_address', 'Can delete address'), ('can_add_address', 'Can add address')], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ('name',), 'permissions': [('can_view_comuna', 'Can view comuna'), ('can_edit_comuna', 'Can edit comuna'), ('can_delete_comuna', 'Can delete comuna'), ('can_add_comuna', 'Can add comuna')], 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('name',), 'permissions': [('can_view_province', 'Can view province'), ('can_edit_province', 'Can edit province'), ('can_delete_province', 'Can delete province'), ('can_add_province', 'Can add province')], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('number',), 'permissions': [('can_add_region', 'Can add region'), ('can_view_region', 'Can view region'), ('can_edit_region', 'Can edit region'), ('can_delete_region', 'Can delete region')], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
    ]
