# Generated by Django 5.2 on 2025-05-22 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product category.', max_length=255, unique=True, verbose_name='Product Category Name')),
                ('slug', models.SlugField(help_text='A short label for URL configuration.', max_length=255, unique=True, verbose_name='Product Category Slug')),
                ('description', models.TextField(blank=True, default='', help_text='A brief description of the category.', verbose_name='Product Category Description')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['name'],
                'permissions': [('can_view_product_category', 'Can view product category'), ('can_edit_product_category', 'Can edit product category'), ('can_delete_product_category', 'Can delete product category')],
                'indexes': [models.Index(fields=['name'], name='idx_product_category_name'), models.Index(fields=['slug'], name='idx_product_category_slug')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_product_category_name')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255, unique=True, verbose_name='Product Name')),
                ('slug', models.SlugField(help_text='A short label for URL configuration.', max_length=255, unique=True, verbose_name='Product Slug')),
                ('description', models.TextField(blank=True, default='', help_text='A brief description of the product.', verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product.', max_digits=10, verbose_name='Product Price')),
                ('category', models.ForeignKey(help_text='The category to which the product belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'permissions': [('can_view_product', 'Can view product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product')],
                'indexes': [models.Index(fields=['name'], name='product_name_idx'), models.Index(fields=['slug'], name='product_slug_idx')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_product_name'), models.UniqueConstraint(fields=('slug',), name='unique_product_slug')],
            },
        ),
    ]
