# Generated by Django 5.2 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'permissions': [('can_view_product', 'Can view product'), ('can_edit_product', 'Can edit product'), ('can_delete_product', 'Can delete product'), ('can_add_product', 'Can add product')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'permissions': [('can_view_product_category', 'Can view product category'), ('can_edit_product_category', 'Can edit product category'), ('can_delete_product_category', 'Can delete product category'), ('can_add_product_category', 'Can add product category')], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
