# Generated by Django 5.2 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'permissions': [('can_view_warehouse', 'Can view warehouse'), ('can_edit_warehouse', 'Can edit warehouse'), ('can_delete_warehouse', 'Can delete warehouse'), ('can_add_warehouse', 'Can add warehouse')], 'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterModelOptions(
            name='warehouseemployee',
            options={'ordering': ['employee__last_name', 'employee__first_name'], 'permissions': [('can_view_warehouse_employee', 'Can view warehouse employee'), ('can_edit_warehouse_employee', 'Can edit warehouse employee'), ('can_delete_warehouse_employee', 'Can delete warehouse employee'), ('can_add_warehouse_employee', 'Can add warehouse employee')], 'verbose_name': 'Warehouse Employee', 'verbose_name_plural': 'Warehouse Employees'},
        ),
        migrations.AlterModelOptions(
            name='warehouseinventory',
            options={'ordering': ['product__name', 'warehouse__name'], 'permissions': [('can_view_warehouse_inventory', 'Can view warehouse inventory'), ('can_edit_warehouse_inventory', 'Can edit warehouse inventory'), ('can_delete_warehouse_inventory', 'Can delete warehouse inventory'), ('can_add_warehouse_inventory', 'Can add warehouse inventory')], 'verbose_name': 'Warehouse Inventory', 'verbose_name_plural': 'Warehouse Inventories'},
        ),
    ]
