# Generated by Django 5.2 on 2025-05-22 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.ForeignKey(help_text='The address of the warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='addresses.address', verbose_name='Warehouse Address'),
        ),
    ]
