# Generated by Django 5.2 on 2025-05-21 23:08

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('slug', models.CharField(help_text='The slug of the group.', max_length=255, unique=True, verbose_name='Group slug')),
                ('description', models.CharField(blank=True, help_text='The description of the group.', max_length=255, verbose_name='Group description')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_group_name'), models.UniqueConstraint(fields=('slug',), name='unique_group_slug')],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
