# Generated by Django 5.2 on 2025-05-22 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="The person's first name.", max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="The person's last name.", max_length=255, verbose_name='Last Name')),
                ('email', models.EmailField(help_text="The person's email address.", max_length=254, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, default='', help_text="The person's phone number.", max_length=20, verbose_name='Phone Number')),
                ('address', models.ForeignKey(help_text='The address of the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='addresses.address', verbose_name='Customer Address')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['first_name', 'last_name'],
                'permissions': [('can_view_customer', 'Can view customer'), ('can_edit_customer', 'Can edit customer'), ('can_delete_customer', 'Can delete customer')],
                'indexes': [models.Index(fields=['first_name'], name='idx_customer_first_name'), models.Index(fields=['last_name'], name='idx_customer_last_name')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_customer_email'), models.UniqueConstraint(fields=('phone_number',), name='unique_customer_phone_number')],
            },
        ),
    ]
