# Generated by Django 5.2 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_view_customer', 'Can view customer'), ('can_edit_customer', 'Can edit customer'), ('can_delete_customer', 'Can delete customer'), ('can_add_customer', 'Can add customer')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
