# Generated by Django 5.2 on 2025-05-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_class',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale')], default='retail', help_text='The class of customer (retail, wholesale, etc.).', max_length=20, verbose_name='Customer Class'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('government', 'Government'), ('non_profit', 'Non-Profit'), ('other', 'Other')], default='individual', help_text='The type of customer (individual, company, etc.).', max_length=20, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rut',
            field=models.CharField(default='', help_text="The person's RUT (Rol Único Tributario).", max_length=13, unique=True, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
