# Generated by Django 5.2 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeemployee',
            options={'ordering': ['store__name', 'employee__last_name', 'employee__first_name'], 'permissions': [('can_view_store_employee', 'Can view store employee'), ('can_edit_store_employee', 'Can edit store employee'), ('can_delete_store_employee', 'Can delete store employee'), ('can_add_store_employee', 'Can add store employee')], 'verbose_name': 'Store Employee', 'verbose_name_plural': 'Store Employees'},
        ),
    ]
