# Generated by Django 5.2 on 2025-05-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_sale', 'Can view sale'), ('can_edit_sale', 'Can edit sale'), ('can_delete_sale', 'Can delete sale'), ('can_add_sale', 'Can add sale')], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['sale', 'product'], 'permissions': [('can_view_sale_item', 'Can view sale item'), ('can_edit_sale_item', 'Can edit sale item'), ('can_delete_sale_item', 'Can delete sale item'), ('can_add_sale_item', 'Can add sale item')], 'verbose_name': 'Sale Item', 'verbose_name_plural': 'Sale Items'},
        ),
    ]
